# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.
# Your application's name

appname: "pubmedBatch"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '[%'
      end_tag:   '%]'
plugins:
    ProgressStatus:
        dir:  "temp/dancer_progress"
    Database:
        connections:
            pubmedBatch:
                driver: "SQLite"
                database: 'db/pubmedBatch.sqlite'
                dbi_params:
                    sqlite_unicode: 1
fields:
    AND: "dominant"
    OR: "retina retinal retinitis blindness macula macular stargardt"
# record life (in second)
# currently keeps record for 14 days
life: 1209600
